### ISSUE TITLE
ImportError: /home/mpl/.local/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by landy-hu** [ohosseini/DOCS-pytorch#1]
when i run the order, "bash demo.sh " in the terminator, there will be a error as following

> /home/mpl/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> /home/mpl/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> Traceback (most recent call last):
>   File "demo.py", line 8, in <module>
>     from models.docs import DOCSNet
>   File "/home/mpl/DOCS-pytorch/models/docs.py", line 6, in <module>
>     from .correlation_package.correlation import Correlation
>   File "/home/mpl/DOCS-pytorch/models/correlation_package/correlation.py", line 4, in <module>
>     import correlation_cuda
> ImportError: /home/mpl/.local/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

and i have check, under the path, there exactly exist the correlation_cuda.cpython-36m-x86_64-linux-gnu.so file.   and i have add the path /home/mpl/.local/lib to the ~/.bashrc file.  Thanks for your reply

**Comment by ohosseini** [comment]
Could you please let me know which version of PyTorch and numpy are you using?

You can run:
`conda list | grep 'pytorch\|numpy'`

**Comment by landy-hu** [comment]
thanks, i have solved the problem, which seemly  was caused by the gcc version

**Comment by Jli560** [comment]
Hello, I met the same problem recently, are you able to tell me which gcc version did you use at that time? I tried gcc 7.3, gcc 6.5 and gcc 7.5, but still have the same problem. Thank you so much.

**Comment by ohosseini** [comment]
> Hello, I met the same problem recently, are you able to tell me which gcc version did you use at that time? I tried gcc 7.3, gcc 6.5 and gcc 7.5, but still have the same problem. Thank you so much.

Hi, I used 4.9 at that time. These errors are all related to correlation module. You can follow the [issues](https://github.com/NVIDIA/flownet2-pytorch/issues) in that repository.

**Comment by Jli560** [comment]
> > Hello, I met the same problem recently, are you able to tell me which gcc version did you use at that time? I tried gcc 7.3, gcc 6.5 and gcc 7.5, but still have the same problem. Thank you so much.
> 
> Hi, I used 4.9 at that time. These errors are all related to correlation module. You can follow the [issues](https://github.com/NVIDIA/flownet2-pytorch/issues) in that repository.

Thank you so much for your quick response. I tried 5.5 just now and still have the same error. I will try 4.9 now. Thank you so much.

**Comment by Jli560** [comment]
> > Hello, I met the same problem recently, are you able to tell me which gcc version did you use at that time? I tried gcc 7.3, gcc 6.5 and gcc 7.5, but still have the same problem. Thank you so much.
> 
> Hi, I used 4.9 at that time. These errors are all related to correlation module. You can follow the [issues](https://github.com/NVIDIA/flownet2-pytorch/issues) in that repository.

Hi @ohosseini , are you able to tell me which cuda version did you use? I solved the previous problem but met a new problem:
ImportError: /home/lijiahao/anaconda3/envs/python36/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration


I guess it is because of my cuda version. Thank you.

**Comment by ohosseini** [comment]
I used CUDA 8 or 9, I don't remember right now.
But I just made a new version of correlation module which is working with the latest version of pytorch (1.6), cuda 10.2 and gcc 8.0.
I tested it on Ubuntu 20.04 and it is working. I will update the repository soon.

**Comment by Jli560** [comment]
> I used CUDA 8 or 9, I don't remember right now.
> But I just made a new version of correlation module which is working with the latest version of pytorch (1.6), cuda 10.2 and gcc 8.0.
> I tested it on Ubuntu 20.04 and it is working. I will update the repository soon.

Thank you for your help. I have to use pytorch 0.4.1 now because of some special requirements. And my cuda version is 9.2, will try 9.0 and cuda 8 now.

**Comment by ohosseini** [comment]
> Thank you for your help. I have to use pytorch 0.4.1 now because of some special requirements. And my cuda version is 9.2, will try 9.0 and cuda 8 now.

Yes, it may solve your problem. I just pushed the changes. I also released and tagged the old version, so you can clone it at any time from [here](https://github.com/ohosseini/DOCS-pytorch/tree/v1.0).

**Comment by Jli560** [comment]
> > Thank you for your help. I have to use pytorch 0.4.1 now because of some special requirements. And my cuda version is 9.2, will try 9.0 and cuda 8 now.
> 
> Yes, it may solve your problem. I just pushed the changes. I also released and tagged the old version, so you can clone it at any time from [here](https://github.com/ohosseini/DOCS-pytorch/tree/v1.0).

I will try it now, thank you a lot for your help.

**Comment by Jli560** [comment]
> > Thank you for your help. I have to use pytorch 0.4.1 now because of some special requirements. And my cuda version is 9.2, will try 9.0 and cuda 8 now.
> 
> Yes, it may solve your problem. I just pushed the changes. I also released and tagged the old version, so you can clone it at any time from [here](https://github.com/ohosseini/DOCS-pytorch/tree/v1.0).

I just tried cuda 9.0 with gcc 4.9 and everything is good now. Thank you for your help @ohosseini
