### ISSUE TITLE
I met this error when run install.sh in my ubuntu19.10.

### ISSUE THREAD

**Issue by bemoregt** [ohosseini/DOCS-pytorch#2]
Hi, @ohosseini 

I met this error when run install.sh in my ubuntu19.10.

kerbal@msi:~/Desktop/DOCS-pytorch$ ./install.sh 
running install
running bdist_egg
running egg_info
writing correlation_cuda.egg-info/PKG-INFO
writing dependency_links to correlation_cuda.egg-info/dependency_links.txt
writing top-level names to correlation_cuda.egg-info/top_level.txt
reading manifest file 'correlation_cuda.egg-info/SOURCES.txt'
writing manifest file 'correlation_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'correlation_cuda' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c correlation_cuda.cc -o build/temp.linux-x86_64-3.6/correlation_cuda.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=correlation_cuda -D_GLIBCXX_USE_CXX11_ABI=0
In file included from correlation_cuda.cc:1:0:
/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/torch.h:11:4: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #  warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h"
    ^~~~~~~
correlation_cuda.cc: In function ‘int correlation_forward_cuda(at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, int, int, int, int, int, int)’:
correlation_cuda.cc:73:25: error: ‘class at::Context’ has no member named ‘getCurrentCUDAStream’
     at::globalContext().getCurrentCUDAStream()
                         ^~~~~~~~~~~~~~~~~~~~
correlation_cuda.cc: In function ‘int correlation_backward_cuda(at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, int, int, int, int, int, int)’:
correlation_cuda.cc:154:69: error: ‘class at::Context’ has no member named ‘getCurrentCUDAStream’
                                                 at::globalContext().getCurrentCUDAStream()
                                                                     ^~~~~~~~~~~~~~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

What's wrong to me ?

Thanks.
Best,
@bemoregt.

**Comment by ohosseini** [comment]
Hi @bemoregt,

which version of CUDA and pytorch are you using?

**Comment by bemoregt** [comment]
Hi, @ohosseini 

Ubuntu 19.10
CUDA 10.1
RTX 2080ti  x2
pytorch 1.4.0
torchvision 0.5.0

Thanks
Best,
@bemoregt

**Comment by ohosseini** [comment]
Can you give it a try with pytorch 0.4? I never tried it on 1.4 and the error is related to NVIDIA implementation of correlation layer ([link](https://github.com/NVIDIA/flownet2-pytorch)).

**Comment by ohosseini** [comment]
I just updated the correlation package. It is working with pytorch 1+ and higher versions of cuda now.
